---
title: "Project Abstract for January 23"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

Hybrid vigour or heterosis is the improved quality or trait in the offspring as a result of mixing the genetic contributions of its parents. As an illustration, brocoli have flowers that pack densely to form the head which is the main edible part of the plant. When breeding disimillar strains of brocoli their offspring can form much larger heads of brocoli. Li et al. [2018](https://bmcplantbiol.biomedcentral.com/articles/10.1186/s12870-018-1384-4) crossed parental lines and demonstrated heterosis in their offspring, shown in [figure 1](https://camo.githubusercontent.com/e51928dfa71bf6d08d808830a5ab5eb14d92de39/68747470733a2f2f73636f6e74656e742e66796b61312d312e666e612e666263646e2e6e65742f762f74312e302d392f34393231333430385f31303231383037373735373931363234315f323434303739383231373435383135353532305f6e2e6a70673f5f6e635f6361743d313131265f6e635f68743d73636f6e74656e742e66796b61312d312e666e61266f683d6436376132613165633534313537353935613733323064386362656433626333266f653d3543464230373446). In their study they used 2 sets of triads (2 parent 1 child) to clearly demonstrate heterosis. As a result the sample size is 4 parents and 2 offsprig. However, despite the small sample size heterosis was clearly demonstrated in their offspring. Moreover, the parental lines were self-bred for six generations to produce confidently homozygous seed of one genetic background. For this reason, we believe analyzing this dataset will be okay.

The data transcriptomic and methylomic data associated with this paper can be found [here](https://static-content.springer.com/esm/art%3A10.1186%2Fs12870-018-1384-4/MediaObjects/12870_2018_1384_MOESM2_ESM.zip). For a detailed description of the data we have written it up here [...](https://github.com/glenn-mcguinness/stat540FinalProject/blob/master/Data/data_description.md). 

**Is there differential expression between parents and offspring that are contributing to heterosis?** For our project, we will analyze Li et al's RNA-seq data from the parents and offspring and to check if the parents and children cluster independently or with each other. We will also check for differential expression between the parents and offspring. Becasue there are two backgrounds of parents NKR and BRO, we will check if parental background is a factor. We can then group the DE genes based on GO annotations.

**To what degree could heterosis be regulated by epigenetics as seeen through methylation data?** Based on genes that are differentially expressed between the parents and the hybrid offspring, we can check if there is differential methylation between the parents and the offspring near that gene and if the paternal line contribute more than the maternal line. 